### ISSUE TITLE
Convert camelCase into --camel-case type flags automatically

### ISSUE THREAD

**Issue by mikehearn** [xenomachina/kotlin-argparser#14]
It'd be nice if I didn't have to specify a custom name for that.

**Comment by xenomachina** [comment]
I agree. That should probably be the default behavior. Perhaps it should also be possible to specify a "name transformer" function when creating an `ArgParser`, in case someone doesn't like the default conversion.

**Comment by xenomachina** [comment]
I've made this change.

For options, "camelCase" turns into "--camelCase".

For positional arguments (and option argNames), "camelCase" turns into "CAMEL-CASE".

**Comment by mikehearn** [comment]
Is your last comment correct? camelCase already turns into --camelCase, the request was for --non-camel-case

**Comment by xenomachina** [comment]
Whoops! No, that was wrong. Thanks for catching that.

For options, "camelCase" turns into "--camel-case".

For positional arguments (and option argNames), "camelCase" turns into "CAMEL-CASE".

(I also corrected the original comment, to avoid future confusion.)
