### ISSUE TITLE
Can't specify 'argName' on 'storing' without a transform lambda.

### ISSUE THREAD

**Issue by JakeWharton** [xenomachina/kotlin-argparser#15]
Seems like there should still be a default that does strings even if I want to provide a better argument name.

**Comment by xenomachina** [comment]
Good catch! Yes, it looks like I missed a couple of the `storing` and also one of the `adding` methods when adding the `argName` parameter. I've pushed a commit that fixes this. I'll try to release an update with this fix tomorrow.

**Comment by JakeWharton** [comment]
Thanks! 2.0 is otherwise a great improvement thus far.

**Comment by xenomachina** [comment]
Thank you!
