### ISSUE TITLE
Document package name and import

### ISSUE THREAD

**Issue by DALDEI** [xenomachina/kotlin-argparser#26]
The docs and examples do not include any reference to what imports or package is used.
they should have a reference to  

 import com.xenomachina.argparser.* ; 

( no its not entirely obvious without scraping the code )

**Comment by xenomachina** [comment]
Good point. I'll be sure to add it somewhere in the README. I'm also looking into ways to host the KDocs, which should also help. (For now, I've added the docs jar file as a binary for the latest release.)

Out of curiosity, are you using an IDE?
