### ISSUE TITLE
Help text needs to be properly formatted

### ISSUE THREAD

**Issue by xenomachina** [xenomachina/kotlin-argparser#3]
Help text currently isn't word-wrapped, and the indentation for the argument types just uses tab, which is terrible.

**Comment by mikehearn** [comment]
It'd be great if you could provide some screenshots showing what a program that uses argparse looks like to the user, both help text and errors when the args are wrong.

**Comment by xenomachina** [comment]
@mikehearn I 100% agree. I will file a separate issue for that.

**Comment by xenomachina** [comment]
Fixed by 1764842c3e39beb5e7810bffc43ed5cb494fe48b
