### ISSUE TITLE
Argument optional or mandatory depend on another argument

### ISSUE THREAD

**Issue by JcMinarro** [xenomachina/kotlin-argparser#36]
I would like to write a CLI that accept two different type of argument, and one argument needs another attribute. Let me show an example

```
// This command is going to show the info of the program, doesn't need any extra argument to show it
myProg -i

// This command is going to show the info of a transaction and need the transaction id
myProg --showTransactionInfo --transactionId 3
```

`transactionId` is not needed for the argument `-i` but it is mandatory for the argument `showTransactionInfo`

How could I code it?

**Comment by xenomachina** [comment]
For more complex validation like this, where the presence of one option requires the existence of another option, you can use [`addValidator`](https://github.com/xenomachina/kotlin-argparser#modifying-delegates) to add logic that checks that `--transactionId` has been set whenever `--showTransactionInfo` is passed.

You could also perform the check inside `mainBody`.

Either way, throw a `SystemExitException` to indicate the error.
