### ISSUE TITLE
Maven not downloading .jar from bintray

### ISSUE THREAD

**Issue by seanfdnn** [xenomachina/kotlin-argparser#50]
I've added the Bintray maven dependency but the argparse libraries are not in my path... only the xenocom ones are (xenomachina.text and .common)

I'm not a Maven expert, but I had a look at the .pom on Bintray -- I see the Xenocom dependency in there -- maybe there's something misconfigured or not pointing to the argparse jar?

**Comment by xenomachina** [comment]
Unfortunately, I have almost no experience with Maven (I only use gradle), so I'm not sure if I'll be able to help, but would it be possible for you to post a build file that reproduces the problem? Also, what exact error message are you getting, and is it at compile time or run time?

**Comment by pcoltau** [comment]
I have the same issue. There are two solutions for this:

1) Upload the project to the central maven repository, following this guide: https://maven.apache.org/guides/mini/guide-central-repository-upload.html

or

2) Use jitpack.io as a maven repository. Jitpack.io is a package repository for git and will make a maven jar dependency from most java projects in git: https://jitpack.io/#xenomachina/kotlin-argparser

The second option is the easiest solution right now, but it's not an "official" maven release of this project, which it really deserves to have.

**Comment by pcoltau** [comment]
This guide for publishing a release to a maven repository seems to be more hands-on: https://maven.apache.org/guides/mini/guide-3rd-party-jars-remote.html

**Comment by xenomachina** [comment]
Thanks for the info! Is it really not possible to have Maven pull from jcenter? [This video](https://youtu.be/uFE6M4X8Sqk) seems to suggest that it's possible, but requires updating your maven settings (not ideal -- gradle's approach of having this in the project's build makes more sense, IMHO).

In any case, it probably is about time I put this project up on Maven Central. I found this [tutorial for using Bintray as a gateway to Maven Central](https://blog.bintray.com/2014/02/11/bintray-as-pain-free-gateway-to-maven-central/), so I'm working through that.

**Comment by seanfdnn** [comment]
Sorry I couldn't be more help! After using pip and npm, this is the first project I've used Maven (or Gradle) for so I'm fumbling my way through it too.

**Comment by xenomachina** [comment]
Ok, I've finally gotten around to getting these up on maven central. Sorry it took a while.

    https://mvnrepository.com/search?q=xenomachina

Feel free to reopen if you're still having issues related to this.
