### ISSUE TITLE
Default values with null not working

### ISSUE THREAD

**Issue by godzsa** [xenomachina/kotlin-argparser#51]
When I try to define an argument like this:
`val myVal by parser.storing(help = "Help").default(null)`
I get an error:
`Null can not be a value of a non-null type () -> String` even if I explicitly define it as `String?`

I use version 2.0.4

**Comment by xenomachina** [comment]
Sorry for the slow reply.

Unfortunately, Kotlin seems to have some trouble inferring the right type here without some help. If you specify the nullable type on the call to `default` it should work:

```
val myVal by parser.storing(help = "Help").default<String?>(null)
```

**Comment by commonsguy** [comment]
FWIW, I suggest updating the documentation to show this syntax.
