### ISSUE TITLE
Allow '.' as Separator in Options and Arguments

### ISSUE THREAD

**Issue by tgockel** [xenomachina/kotlin-argparser#54]
The paradigm used for "advanced" options at my company uses namespace-qualified option names on the command line. A la:

    java -jar my-program.jar --com.foo.bar=100 --com.foo.baz=taco

Specifying these as options will always throw `IllegalArgumentException`, as this does not pass the `OPTION_NAME_RE` pattern in `ArgParser.kt`. Is there any reason to _prevent_ using `'.'` as part of an option or argument (sibling to the `'_'` and `'-'` characters)?

**Comment by tgockel** [comment]
Also made a PR because the fix seems super easy. Not sure if disallowing `'.'` characters was intentional or just not done.

**Comment by xenomachina** [comment]
I was reserving the dot for a future feature I've been planning, but after thinking on it, I believe it should be fine to allow it in the way your PR enables.

Thanks for the suggestion, and the PR!
