### ISSUE TITLE
Is it possible to allow number parameters

### ISSUE THREAD

**Issue by oshai** [xenomachina/kotlin-argparser#58]
similar to `tail -100` is it possible to have a number param like `-<number>`?

**Comment by xenomachina** [comment]
This is not currently possible, but it's an interesting idea. Any thoughts on what the API should look like?

Here's something interesting: `tail --help` (from GNU coreutils 8.25) makes no mention of the fact that you can say `-NUMBER` instead of `-nNUMBER`.

**Comment by oshai** [comment]
I thought about numeric similar to flagging.
In Wikipedia this is mentioned as obselete: https://en.m.wikipedia.org/wiki/Tail_(Unix)

**Comment by xenomachina** [comment]
The fact that this is an obsolete syntax makes me inclined to say we shouldn't support it.

If it was supported, you'd only ever be able to create one per command line. I suspect that it would also be difficult to get it to play nice with hierarchical arguments (#56) which, I'd really like to implement at some point.
